# Generated by Django 5.2.14 on 2026-05-14 13:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EncodedMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_image_name', models.CharField(max_length=255)),
                ('encoded_image', models.ImageField(upload_to='encoded_images/')),
                ('secret_key_hash', models.CharField(max_length=128)),
                ('image_key_hash', models.CharField(max_length=128)),
                ('encrypted_message', models.TextField()),
                ('receiver_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('failed_attempts', models.IntegerField(default=0)),
                ('temporary_locked_until', models.DateTimeField(blank=True, null=True)),
                ('is_permanently_locked', models.BooleanField(default=False)),
                ('secret_key_deleted', models.BooleanField(default=False)),
                ('secret_key_deleted_at', models.DateTimeField(blank=True, null=True)),
                ('mse_value', models.FloatField(default=0)),
                ('psnr_value', models.FloatField(default=0)),
                ('ssim_value', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
