# Generated by Django 5.2.14 on 2026-05-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganographyapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedmessage',
            name='image_id',
            field=models.CharField(default=1, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
