# Generated by Django 5.2.14 on 2026-05-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganographyapp', '0002_encodedmessage_image_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='encodedmessage',
            name='decoded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encodedmessage',
            name='is_decoded',
            field=models.BooleanField(default=False),
        ),
    ]
