# Generated by Django 5.2.14 on 2026-05-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('steganographyapp', '0003_encodedmessage_decoded_at_encodedmessage_is_decoded'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='encodedmessage',
            name='secret_key_deleted_at',
        ),
        migrations.AddField(
            model_name='encodedmessage',
            name='image_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encodedmessage',
            name='secret_key_encrypted',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='encodedmessage',
            name='unfreeze_token',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='encodedmessage',
            name='unfreeze_token_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encodedmessage',
            name='image_key_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encodedmessage',
            name='mse_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encodedmessage',
            name='psnr_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='encodedmessage',
            name='secret_key_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='encodedmessage',
            name='ssim_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
